export = {
  INIT_RECORDER: 'MEDIA_RECORDER::INIT_RECORDER',
  REQUEST_RECORDING: 'MEDIA_RECORDER::REQUEST_RECORDING',
  START_RECORDING: 'MEDIA_RECORDER::START_RECORDING',
  STOP_RECORDING: 'MEDIA_RECORDER::STOP_RECORDING',
  ON_START_RECORDING: 'MEDIA_RECORDER::ON_START_RECORDING',
  ON_STOP_RECORDING: 'MEDIA_RECORDER::ON_STOP_RECORDING',
  ON_DATA_AVAILABLE: 'MEDIA_RECORDER::ON_DATA_AVAILABLE',
  ON_COUNT_DOWN: 'MEDIA_RECORDER::ON_COUNT_DOWN',
  DISPOSE_RECORDER: 'MEDIA_RECORDER::DISPOSE_RECORDER'
} as const
