export = {
  REQUEST_GET: 'PERMANENT_STORAGE::REQUEST_GET',
  REQUEST_PUT: 'PERMANENT_STORAGE::REQUEST_PUT',
  ON_SUCCESS_GET: 'PERMANENT_STORAGE::ON_SUCCESS_GET',
  ON_SUCCESS_PUT: 'PERMANENT_STORAGE::ON_SUCCESS_PUT',
  ON_FAILED_GET: 'PERMANENT_STORAGE::ON_FAILED_GET',
  ON_FAILED_PUT: 'PERMANENT_STORAGE::ON_FAILED_PUT'
} as const
