export = {
  INIT_NFC_READER: 'NFC::INIT_NFC_READER',
  INIT_NFC_WRITER: 'NFC::INIT_NFC_WRITER',
  SET_IS_WRITING: 'NFC::SET_IS_WRITING',
  WRITE_DATA: 'NFC::WRITE_DATA',
  ON_READING_EVENT: 'NFC::ON_READING_EVENT',
  ON_COMPLETE_WRITE: 'NFC::ON_COMPLETE_WRITE',
  ON_ERROR_READ: 'NFC::ON_ERROR_READ',
  ON_ERROR_WRITE: 'NFC::ON_ERROR_WRITE',
} as const
