export = {
  SET_ENABLED_PERMISSION_API: 'PERMISSION_STATE::SET_ENABLED_PERMISSION_API',
  SET_PERMISSION_STATE: 'PERMISSION_STATE::SET_PERMISSION_STATE',
  REQUEST_PERMISSION: 'PERMISSION_STATE::REQUEST_PERMISSION',
  RESOLVE_PERMISSION: 'PERMISSION_STATE::RESOLVE_PERMISSION',
  RESOLVED_PERMISSION: 'PERMISSION_STATE::RESOLVED_PERMISSION'
} as const
